USE [SaudeSJRP]
GO

/*** Índice criado em 10/08/2023
CREATE INDEX [IX_ATEN_27]
ON [SaudeSJRP].[dbo].[TB_AT_ATENDIMENTO] ([DT_INCLUSAO])

CREATE INDEX [IX_TB_AT_REGULACAO_IC_SITUACAO_F86B9]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])

/*** Índice criado em 01/08/2023
CREATE INDEX [IX_PF_PRONTUARIO_01]
ON [SaudeSJRP].[dbo].[TB_PF_PRONTUARIO] ([DT_INCLUSAO])

*** Índice criado em 20/07/2023
CREATE INDEX [IX_AT_RE_18]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])

*** Índice criado em 20/06/2023

CREATE NONCLUSTERED INDEX [IX_AP_AGPR_03]
ON [dbo].[TB_AP_AGENDA_PROCEDIMENTO] ([CD_PROCEDIMENTO],[IC_SITUACAO])
INCLUDE ([CD_AGENDA_PROFISSIONAL],[CD_AGENDA_PROCEDIMENTO],[CD_PESSOA_ESTABELECIMENTO],[CD_VINCPROF_SERV_PRESTADO],[CD_ES_SERVICO_PRESTADO])
GO


*** índice criado em 11/04/2023

CREATE NONCLUSTERED INDEX [IX_TB_SI_LT_MAT_02]
ON [dbo].[TB_SICOM_LOTE_MATERIAL] ([MATE_COD_MATERIAL],[LOMA_SEQ_LOTE])


*** índices criados em 09/03/2023

CREATE INDEX [IX_AT_RE_17]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])

*** índices criados em 09/03/2023

CREATE INDEX [IX_AT_RE_16]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])

CREATE INDEX [IX_LB_EXAME_SOLICITACAO_17]
ON [SaudeSJRP].[dbo].[TB_LB_EXAME_SOLICITACAO] ([CD_ESTABELECIMENTO_COLETA], [CD_AGENDA_PROFISSIONAL])
INCLUDE ([CD_USUARIO_SAUDE], [IC_ATIVO], [IC_FATURA_UNIDADE], [CD_RECEPCAO_COLETA], [CD_ATENDIMENTO_COLETA])


*** índices criados em 22/02-2023

CREATE INDEX [IX_TB_SICOM_UNIDADES_X_MATERIAIS_01]
ON [SaudeSJRP].[dbo].[TB_SICOM_UNIDADES_X_MATERIAIS] ([UNID_COD_UNIDADE])
INCLUDE ([INST_NUM_INSTITUICAO], [UNID_COD_UNIDADE_ALMOX_RESP], [MATE_COD_MATERIAL])

CREATE INDEX [IX_AT_RE_15]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])

CREATE INDEX [IX_TB_SICOM_UNIDADES_X_MATERIAIS_02]
ON [SaudeSJRP].[dbo].[TB_SICOM_UNIDADES_X_MATERIAIS] ([UNID_COD_UNIDADE], [MATE_COD_MATERIAL])
INCLUDE ([INST_NUM_INSTITUICAO], [UNID_COD_UNIDADE_ALMOX_RESP])

*** índices criados em 25/11/2022

CREATE INDEX [IX_MA_MO_02]
ON [SaudeSJRP].[dbo].[TB_MM_MATERIAL_MOVIMENTO] ([CD_PESSOA], [IC_ATIVO], [CD_PESSOA_ESTABELECIMENTO],[DT_MOVIMENTO])
INCLUDE ([CD_MATERIAL_MOVIMENTO], [CD_TIPO_MOVIMENTO], [IC_SITUACAO], [CD_PESSOA_USUARIO_SAUDE], [CD_ALMOXARIFADO_PAI], [CD_MATERIAL_MOVIMENTO_PAI], [CD_PRESCRICAO], [CD_CENTRO_CUSTO], [CD_INVENTARIO_BALANCO], [VL_DOCUMENTO], [DS_OBSERVACAO], [NM_UNIDADE_ORIGEM_EXTERNO], [NM_PROFISSIONAL_EXTERNO], [NM_ESPECIALIDADE_EXTERNO], [VL_SICOM_RQMT_NUM_REQUISICAO], [VL_SICOM_UNID_COD_UNIDADE], [IC_ALTERADO_SICOM])
GO

CREATE INDEX [IX_AT_RE_14]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])
GO

*** índices criados em 11/11/2022

CREATE NONCLUSTERED INDEX [IX_AP_AP_08]
ON [SaudeSJRP].[dbo].[TB_AP_AGENDA_PROFISSIONAL] ([CD_IMPEDE_AGENDA], [CD_GRADE_HORARIO_PROFIS], [CD_VINCPROF_SERV_PRESTADO], [CD_PESSOA_ESTABELECIMENTO], [CD_ES_SERVICO_PRESTADO], [CD_PROGRAMA_GOVERNO], [IC_DISPONIVEL], [IC_ATIVO], [VL_IDADE_FINAL], [VL_IDADE_INICIAL], [IC_TIPO_CONSULTA], [IC_SEXO_PERMITIDO])
INCLUDE ([CD_AGENDA_PROFISSIONAL], [DT_CONSULTA], [IC_SOLICITANTE])
GO

*** índices criados em 09/11/2022

CREATE INDEX [IX_PF_O_05]
ON [SaudeSJRP].[dbo].[TB_PF_OCUPACAO] ([IC_ATIVO])
INCLUDE ([CD_FISICA], [CD_PF_OCUPACAO], [CD_OCUPACAO], [CD_ORGAO_EMISSOR], [VL_NUMERO_CONSELHO])

*** índices criados em 03/11/2022

CREATE INDEX [IX_AT_RE_13]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])


*** índices criados em 01/11/2022

CREATE INDEX [IX_PR_OC_01]
ON [SaudeSJRP].[dbo].[TB_PR_PROCEDIMENTO_OCUPACAO] ([CD_PESSOA], [CD_OCUPACAO], [IC_ATIVO])
INCLUDE ([CD_PROCEDIMENTO], [DT_IMPORTACAO])

*** índices criados em 31/10/2022

CREATE INDEX [IX_AP_AP_12]
ON [SaudeSJRP].[dbo].[TB_AP_AGENDA_PROFISSIONAL] ([IC_DISPONIVEL], [IC_TIPO_CONSULTA],[DT_CONSULTA], [DT_INCLUSAO])
INCLUDE ([CD_AGENDA_PROFISSIONAL])

CREATE INDEX [IX_AT_PR_05]
ON [SaudeSJRP].[dbo].[TB_AT_PRESCRICAO] ([DT_PRESCRICAO])
INCLUDE ([CD_PRESCRICAO], [CD_RECEPCAO], [CD_ATENDIMENTO])


*** índices criados em 17/10/2022

CREATE INDEX [IX_AP_GR_PR_07]
ON [SaudeSJRP].[dbo].[TB_AP_GRADE_PROCEDIMENTO] ([IC_ATIVO])
INCLUDE ([CD_VINCPROF_SERV_PRESTADO], [CD_PESSOA_ESTABELECIMENTO], [CD_ES_SERVICO_PRESTADO], [CD_GRADE_HORARIO_PROFIS], [CD_PROCEDIMENTO])
GO

*** índices criados em 14/10/2022

CREATE INDEX [IX_MA_MO_01]
ON [SaudeSJRP].[dbo].[TB_MM_MATERIAL_MOVIMENTO] ([IC_SITUACAO], [IC_ATIVO], [VL_SICOM_RQMT_NUM_REQUISICAO])
GO

CREATE INDEX [IX_ATEN_26]
ON [SaudeSJRP].[dbo].[TB_AT_ATENDIMENTO] ([CD_PESSOA_USUARIO_SAUDE])
INCLUDE ([CD_RECEPCAO], [CD_ATENDIMENTO], [DT_INCLUSAO], [DT_INICIO_ATENDIMENTO])
GO

CREATE INDEX [IX_AT_RE_12]
ON [SaudeSJRP].[dbo].[TB_AT_REGULACAO] ([IC_SITUACAO])
INCLUDE ([CD_REGULACAO], [CD_PRESCRICAO], [CD_PRESCRICAO_DETALHE])
GO

CREATE INDEX [IX_AP_AP_11]
ON [SaudeSJRP].[dbo].[TB_AP_AGENDA_PROFISSIONAL] ([IC_DISPONIVEL], [IC_TIPO_CONSULTA],[DT_CONSULTA], [DT_INCLUSAO])
INCLUDE ([CD_AGENDA_PROFISSIONAL])
GO

*** índices criados em 06/10/2022

CREATE INDEX [IX_AP_GR_HO_PR_07]
ON [SaudeSJRP].[dbo].[TB_AP_GRADE_HORARIO_PROFIS] ([IC_ATIVO])
INCLUDE ([CD_PESSOA_ESTABELECIMENTO], [CD_VINCPROF_SERV_PRESTADO], [CD_ES_SERVICO_PRESTADO], [CD_GRADE_HORARIO_PROFIS], [IC_COTA_PRIORIDADE])
GO

*** índices criados em 04/10/2022

CREATE INDEX [IX_TB_CO_QUEST_PERG_02]
ON [SaudeSJRP].[dbo].[TB_CO_QUESTIONARIO_PERGUNTA] ([IC_ATIVO])
INCLUDE ([CD_QUESTIONARIO], [CD_PERGUNTA], [CD_QUESTIONARIO_PERGUNTA], [CD_PESSOA])
GO

CREATE INDEX [IX_PF_D_09]
ON [SaudeSJRP].[dbo].[TB_PF_DOCUMENTO] ([IC_ATIVO], [VL_DNV_NUMERO],[CD_FISICA])
INCLUDE ([VL_IDENTIDADE_NUMERO], [VL_IDENTIDADE_COMPLEMENTO], [VL_CPF_NUMERO], [VL_IDENTIFICADOR_MUNICIPIO])
GO

CREATE INDEX [IX_PR_PR_FI_OR_04]
ON [SaudeSJRP].[dbo].[TB_PR_PROGRAMACAO_FISICO_ORC] ([CD_PESSOA_ESTABELECIMENTO], [IC_ATIVO], [IC_FATURA_INDIVIDUALIZADO])
INCLUDE ([CD_PROCEDIMENTO])
GO

CREATE INDEX [IX_AT_INT_01]
ON [SaudeSJRP].[dbo].[TB_AT_INTERCONSULTA] ([CD_USUARIO_SAUDE], [IC_ATIVO])
GO

CREATE INDEX [IX_PE_TEL_01]
ON [SaudeSJRP].[dbo].[TB_PE_TELEFONE] ([CD_PESSOA], [IC_ATIVO])
INCLUDE ([CD_TELEFONE], [VL_DDD], [VL_PREFIXO], [VL_SUFIXO], [IC_TIPO_TELEFONE])
GO

CREATE INDEX [IX_MM_MAT_MOV_02]
ON [SaudeSJRP].[dbo].[TB_MM_MAT_MOVIMENTO_DET_LOTE] ([CD_MATERIAL_MOVIMENTO], [CD_MATERIAL_MOVIMENTO_DET])
INCLUDE ([CD_MAT_MOVIMENTO_DET_LOTE], [VL_QTDE_MOVIMENTO], [VL_SICOM_LOMA_SEQ_LOTE])
GO

CREATE INDEX [IX_MM_MAT_MOV_03]
ON [SaudeSJRP].[dbo].[TB_MM_MAT_MOVIMENTO_DET_LOTE] ([CD_MATERIAL_MOVIMENTO], [CD_MATERIAL_MOVIMENTO_DET])
INCLUDE ([CD_MAT_MOVIMENTO_DET_LOTE], [VL_QTDE_MOVIMENTO], [VL_SICOM_LOMA_SEQ_LOTE])
GO

*** índices criados em 03/10/2022

CREATE INDEX [IX_PF_FI_10]
ON [SaudeSJRP].[dbo].[TB_PF_FISICA] ([CD_FISICA_SUCESSOR])
INCLUDE ([CD_FISICA], [CD_PESSOA], [NM_PESSOA], [DT_NASCIMENTO], [IC_SEXO], [IC_ATIVO], [DT_INCLUSAO], [CD_USUARIO_INCLUSAO], [CD_RACA_COR], [CD_PAIS], [CD_MUNICIPIO_NATURAL], [CD_CODE_CIPHERS], [DT_IMPORTACAO], [NM_MAE], [NM_PAI], [NM_SOCIAL], [NM_SOCIAL_FONETICO], [NM_SOCIAL_SEM_ACENTO], [IC_FREQUENTA_ESCOLA], [IC_SITUACAO], [IC_NACIONALIDADE], [IC_GRUPO_SANGUINEO], [IC_FATOR_RH], [IC_ESTADO_CIVIL], [IC_TRABALHA], [DT_ALTERACAO], [CD_USUARIO_ALTERACAO], [CD_ETNIA], [IC_DEFICIENTE], [IC_INAPTO], [CD_RELIGIAO], [IC_OrientacaoDesejoSexual], [IC_IdentidadeDeGeneroAparencia], [CD_ESTABELECIMENTO_ALTERACAO], [IC_DEFICIENCIA], [STACKTRACE], [IC_MEDIDA_PROTETIVA], [IC_IDOSO_INSTITUCIONALIZADO], [IC_PALIACAO_PLENA])
GO

CREATE INDEX [IX_PF_FI_11]
ON [SaudeSJRP].[dbo].[TB_PF_FISICA] ([IC_ATIVO],[CD_FISICA])
INCLUDE ([CD_PESSOA], [NM_PESSOA], [DT_NASCIMENTO], [IC_SEXO], [NM_MAE], [NM_SOCIAL], [IC_SITUACAO], [IC_DEFICIENTE], [IC_OrientacaoDesejoSexual], [IC_IdentidadeDeGeneroAparencia], [IC_MEDIDA_PROTETIVA], [IC_IDOSO_INSTITUCIONALIZADO], [IC_PALIACAO_PLENA])
GO
*/